### ISSUE TITLE
Simultaneous assignment happens simultaneously

### ISSUE THREAD

**Issue by siddharth-krishna** [wies/grasshopper#12]
The semantics of `x, y := E1, E2;` really seem to be replacing `x` and `y` at the same time. Given that SPL is an imperative language, this leads to potentially strange things like the following program going through:
```
procedure bar(x: Int)
  requires x == 0
  ensures false
{
  x, x := x + 5, x + 6;
}
```

Should we switch to a semantics that assigns `x` first, and then `y`?

**Comment by wies** [comment]
OK. This is definitely a bug that needs to be fixed. I like to keep the simultaneous assignment semantics. Instead, we should add a check in the front-end that checks that all lvalues in this assignments are different. This can be done syntactically as we already forbid simultaneous assignments that affect the heap.

**Comment by dzufferey** [comment]
I agree with Thomas. But just to make sure we are consistent, what is happening to that kind of  assignments in the C code generation?

**Comment by siddharth-krishna** [comment]
Sure, that sounds good. Just curious: where did we need simultaneous
assignment?

The output C program is not using simultaneous semantics right now:
```
void bar (int x) {
  x = (x + 5);
  x = (x + 6);
}
```

Siddharth

**Comment by wies** [comment]
Both of these issues are now fixed in master.
