### ISSUE TITLE
Getting the CI works with recent version of ocaml

### ISSUE THREAD

**Issue by dzufferey** [wies/grasshopper#13]
I was trying to fix some deprecated method warning. (Ubuntu 17.10 uses ocaml 4.04.)
However, I did not manage to get the CI build to work.

The method that poses problems is `String.uppercase_ascii` which came with ocaml 4.03. 4.03 was also the version for the CI script. However, it fails to compile...

I tried `OCAML_VERSION=4.04` just to be sure but it also fails. I suppose the CI script is not configured properly. Did you already had any issue like this before?

**Comment by dzufferey** [comment]
I did some search in the [ocaml ci build script](https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh).
There seems to be something funny going on. It is putting back ocaml version to 4.02 and then try to use opam to compile and use 4.04...

The easy solution is to revert the commit that gave the error or report that as a bug to the developers of the build script.

@wies @siddharth-krishna Does it compile on your machine? Just to make sure it is only a CI issue.

**Comment by wies** [comment]
It compiles on my machine. I am using Debian stable at the moment, which is still on OCaml v. 4.02. I can upgrade to 4.04 or 4.05 if there is an issue with String.uppercase_ascii. I think that function does not yet exist in 4.02.

**Comment by dzufferey** [comment]
you mean compile with 4.02 and `String.uppercase_ascii`?
I committed these changes earlier today.

**Comment by siddharth-krishna** [comment]
I'm using OCaml 4.05, and was able to compile both commit `35b42a5` and `24dafae` successfully. So maybe it's a bug with the CI/CI script?

**Comment by wies** [comment]
Yes, the current version no longer compiles for me with 4.02 due to the use of `String.uppercase_ascii`. Though, I can upgrade ocaml on my machine. We just need to update README.md to reflect the new version requirements.

**Comment by siddharth-krishna** [comment]
If you look at lines 58-59 of [.travis-ocaml.sh](https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh), it looks like if you choose 4.04 it installs 4.02 but then installs 4.04 via `opam switch`. Perhaps something else needs to be done to get `build.sh` to use the opam switch version of ocaml?

**Comment by siddharth-krishna** [comment]
The problem seems to be that `build.sh` is still calling the system version of ocamlc, despite the PATH being set by the `.travis-ocaml.sh` script a few lines above. I'm not sure why!

From the CI log:
```
$ bash build.sh

+ /usr/bin/ocamlc.opt -c -g -annot -bin-annot -I src/main -I src/verifier -I src/util -I src/programs -I src/formulas -I src/prover -I src/backends/smtlib -I src/backends/c -I src/frontends/spl -o src/main/grasshopper.cmo src/main/grasshopper.ml
```

**Comment by wies** [comment]
I was able to fix the problem after figuring out how to get ocamlbuild to use the opam-version of ocamlc.opt on my Debian machine. The only caveat is that we now have a dependency on ocamlfind. I put a note into README.md on how to install it via opam.

**Comment by wies** [comment]
Btw. I bumped up the version requirement for ocaml to 4.05. Siddharth noticed that they added some useful functions to the standard container data types in the standard library, which we can now use.

**Comment by siddharth-krishna** [comment]
Thanks for both!

**Comment by dzufferey** [comment]
Thanks!
