### ISSUE TITLE
Boolean function definitions translated incorrectly

### ISSUE THREAD

**Issue by siddharth-krishna** [wies/grasshopper#17]
If we have a boolean function, like
```
function intValid(x: Int) returns (res: Bool) {
    (x != 2)
}

procedure foo(x: Int)
  requires intValid(x)
  ensures 2 == 1
{}
```

then the generated VC is
```
(forall x^1: Int ::
   (x^1 != 2)) &&
((2 != 1)) &&
((intValid(x)))
```

which is UNSAT..

(bug appears in commit `5a81337` of `language-improvements` but may also be present in master)

**Comment by siddharth-krishna** [comment]
Thanks! I think the bug is also present in function postconditions. For example:

```
function intValid(x: Int) returns (res: Bool)
  ensures x != 3
{
    (x < 2)
}

procedure foo(x: Int)
  requires intValid(x)
  ensures false
{}
```

**Comment by wies** [comment]
This is actually a different bug, or rather a case of "not yet implemented". Currently, function post-conditions are not yet checked against the body of the function. So you have to be careful about what you write and be aware of potential soundness issues. I was planning to fix this in one go when I get around to fixing issue #5. Though, perhaps we should create a separate issue for this, just to raise awareness.

**Comment by siddharth-krishna** [comment]
Ah, thanks. Though I'm a bit confused - the issue I was pointing out is that postconditions are also being translated as `forall x :: x != 3` instead of `forall x :: intValid(x) ==> x != 3`. This is also a side effect of the fact that checking that postconditions are implied by function bodies is not yet implemented?

**Comment by wies** [comment]
Ah, yes, you are right. I misread the example. I'll take a look into this. In the meantime, you can manually guard the ensures clauses in these cases as a workaround.

**Comment by siddharth-krishna** [comment]
Thanks! Sure, I'll do that.
