### ISSUE TITLE
Pure predicates causing type error in frontend

### ISSUE THREAD

**Issue by siddharth-krishna** [wies/grasshopper#21]
Here is an example:

```
datatype FlowDom = pair(fst: Int, snd: Int);

predicate domEq(p1: FlowDom, p2: FlowDom) {
  p1.fst == p2.fst && p1.snd == p2.snd
}

type NodeDom;

struct Node {}

datatype Interface =
  int(inf: Map<Node, FlowDom>,
      fm: Map<Node, Map<Node, FlowDom>>);

predicate intEq(I1: Interface, I2: Interface) {
  (forall x: Node :: domEq(I1.inf[x], I2.inf[x]))
  && true
}


lemma lemma_repl(I: Interface, I1: Interface, p1: FlowDom, p2: FlowDom)
  requires true
  ensures intEq(I, I1) == true
```

This causes the following error (on commit `3b4c0dd0` of branch language-improvements):
```
Error: cannot convert type Permission near position File "/home/siddharth/grasshopper/test.spl", line 23, columns 10-22
```

Note, the error disappears if we write `domEq(I1.inf[x], I2.inf[x]) == true` instead, or if we remove a conjunct from the definition of `domEq`..

**Comment by wies** [comment]
Interestingly, the problem also goes away if the last line is replaced by

```ensures intEq(I, I1)```

Anyway, I'll fix this.

**Comment by siddharth-krishna** [comment]
Ah yes. Unfortunately, if I do that, the symbolic execution engine thinks it is a spatial predicate.. another bug to be fixed. :)
