### ISSUE TITLE
We know too many ADT equalities

### ISSUE THREAD

**Issue by siddharth-krishna** [wies/grasshopper#30]
Consider the following example:
```
options "-propreads -symbexec"

type K
  
datatype Interface =
  int(na: NodeDom)

datatype InrFn = inrfnC(inrdom: Set<Node>)
  
datatype NodeDom = nd(contents: Set<K>, inr: InrFn);

struct Node {}


function nodeabs(x: Node, C: Set<K>) returns (a: NodeDom)
{
  nd(C, inrfnC({x}))
}

define hrep(x, I) {
  hrepSpatial(x) }

function set_of_map(x: Node, i: Int)
  returns (res: Set<K>)

lemma compute_int(x: Node) returns (I: Interface)
  requires acc(x)
  ensures acc(x)
  ensures I.na.contents == set_of_map(x, 0)
{
  I := int(nodeabs(x, set_of_map(x, 0)));
}
```

We are unable to prove the postcondition, even though we realise that `I.na.contents` and `set_of_map(x, 0)` are equal. I think this is because the two terms end up in the same equivalence class, and so the definition of `nodeabs` is instantiated for `I.na.contents` - but unfortunately Z3 doesn't realise they are equal and so cannot prove the set equality. :)

**Comment by wies** [comment]
Hmm, that's strange. We normally add the inferred equalities to the VC, but maybe something got lost in the recent back-end changes. I'll take a look.

**Comment by wies** [comment]
And that was indeed the problem Fixed.

**Comment by siddharth-krishna** [comment]
Thanks! :)
