### ISSUE TITLE
Assume lemmas don't modify fields or global variables?

### ISSUE THREAD

**Issue by siddharth-krishna** [wies/grasshopper#31]
Example:
```
type K;

struct Node {
  var next: Node;
  var len: Int;
  var keys: Array<K>;
  var ptrs: Array<Node>;
}

define hrepSpatial(x) {
  acc(x) &*& acc(x.keys) &*& acc(x.ptrs)
}

datatype FlowDom = fd(ks: Map<K, Int>, ir: Map<K, Int>)

datatype Interface = int(fm: Map<Node, Map<Node, FlowDom>>)

function fm_ind(x: Node) returns (fm: Map<Node, Map<Node, FlowDom>>)

pure predicate intValid(I: Interface)
  
lemma dummy(x: Node, I: Interface, k: K)
  requires (forall y: Node :: I.fm[x][y].ks[k] == 0)
  ensures intValid(I) == true
  // Adding this means the assert goes through but the postcondition fails
  //ensures B == old(B) && x.len == old(x.len)

var B: Int

procedure foo(x: Node, Ix: Interface, k: K)
  requires hrepSpatial(x)
  requires (forall y: Node :: Ix.fm[x][y].ks[k] == 0)
  requires x.len == 2*B
  ensures hrepSpatial(x)
{
  pure assert x.len == 2*B;
  dummy(x, Ix, k);
  pure assert x.len == 2*B;
}
```

The symbolic execution back-end can prove this, because `dummy` has no spatial footprint, so the value of `x.len` doesn't change. But the standard back-end can't prove the assertion after the call to `dummy`. Should we assume that procedures marked as lemmas don't change any state?

Btw, a strange thing happens if I add the commented out postcondition of `dummy`: the assertion goes through but the postcondition of `foo` fails without any debug information.. is that because it's not clear what the footprint of `dummy` is?

**Comment by wies** [comment]
Yes, we should assume that lemmas don't change state (and enforce this using a simple type system in the front-end).

I don't know what's going on in the post-condition. There seems to be no label in the counterexample either, which is strange.

**Comment by wies** [comment]
I fixed the problem with the modifies sets of lemmas. I'll create a separate issue for the problem with the postcondition.
