### ISSUE TITLE
Unable to prove trivial equality involving ADTs

### ISSUE THREAD

**Issue by siddharth-krishna** [wies/grasshopper#33]
I think the issue stems from some other part of the VC, because when I tried to isolate the problem and get a minimal example, it disappeared..

If you can, take a look at the procedure `half_split` in file `tests/spl/reloc/b-link-half-split.spl` in commit `d9d707e` on branch `symb-exec`. The procedure call on line 114 fails the precondition on line 131, even though the assertion on line 112 shows that the same precondition holds. The SMT encoding of the equality is complicated, because it involves ADTs and set equalities, but the same encoding happens if I make a procedure whose pre and post condition is this equality - and that goes through. Any idea what's going on?

**Comment by wies** [comment]
Hmm. What's funny is that if one replace the assert by 

assert emptyInt(x, Ix);

then that also fails. It almost seems like there is something fishy going on with the macro expansion. Though, I haven't looked at the details, yet.

**Comment by wies** [comment]
FYI, I boiled this down to the difference between the following two versions

```
pure assert domEq(Ix.inf[x], domZero()) == true && Ix.na == nd({}, inrfnC({n: Node :: {}}, {x}));
```
and
```
pure assert domEq(Ix.inf[x], domZero()) == true;
pure assert Ix.na == nd({}, inrfnC({n: Node :: {}}, {x}));
```
The first one fails whereas the second one succeeds. My guess would be that this is related to propagation of reads over disjunctions. Perhaps a simple way to work around this is to let your symbolic execution engine split conjunctions into separate proof obligations (i.e. do some limited amount of case splitting).
