### ISSUE TITLE
Sorts Loc and Loc are incompatible

### ISSUE THREAD

**Issue by siddharth-krishna** [wies/grasshopper#36]
Example:
```
struct Node {
  var ptrs: Array<Node>;
}

define heapG(xptrs) {
    (xptrs[0] != null)
}

lemma aaa(x: Node) returns (I: Int)
  requires heapG(x.ptrs.map)
  ensures false
{}
```

Looks like a bug in the type checker when macros are used? The `null` inside the macro definition is given type `Loc Null` in the emitted SMT query:
```
(declare-fun grass_null$3 () (Loc Null))
```

**Comment by siddharth-krishna** [comment]
Or maybe a bug in the programmer. :)

It goes away when I use `heapG(x.ptrs)` in the precondition.

**Comment by wies** [comment]
There was a case where type information wasn't propagated over the .map selector on arrays during type inference. This is fixed now.
