### ISSUE TITLE
printing model fails with `-abspreds` option

### ISSUE THREAD

**Issue by dzufferey** [wies/grasshopper#44]
When using `-abspreds` and `-model model.html`, GRASShopper crashed with `Encountered unexpected definition during model conversion`. This seems to come from `src/backends/smtlib/smtLibSolver.ml`.

**Comment by wies** [comment]
Do you still happen to have the input program causing this issue?

**Comment by dzufferey** [comment]
I pushed the file on the actris branch.
It happens with the list example.
```./grasshopper.native tests/spl/actris/list.spl -v -model model.html -procedure main```
The abspreds option is directly in the file.
