### ISSUE TITLE
An error occurring in the execution of build.sh

### ISSUE THREAD

**Issue by wcphkust** [wies/grasshopper#48]
Hi, the build process failed in MacOS with the configuration: OCaml 4.07.0, OCaml Findlib 1.8.1, z3-solver 4.8.9, CVC4 1.7

The error message is as follows.
```
➜ ./build.sh
+ ocamlfind ocamlc -c -g -annot -bin-annot -I src/prover -I src/formulas -I src/main -I src/verifier -I src/programs -I src/util -I src/backends/c -I src/backends/smtlib -I src/frontends/spl -o src/prover/model.cmo src/prover/model.ml
File "src/prover/model.ml", line 1:
Error: src/util/util.cmi
is not a compiled interface for this version of OCaml.
It seems to be for an older version of OCaml.
Command exited with code 2.
Compilation unsuccessful after building 18 targets (17 cached) in 00:00:00.
```

I checked the versions of these dependencies one by one. It seems that the versions of dependencies are correct. I am quite confused about this error.

**Comment by wies** [comment]
I have seen this happening to me when I compiled for one version of OCaml and then switched to another version without running `build clean`. Can you run `build clean; build` to see whether compiling all files from scratch solves the problem?

**Comment by wcphkust** [comment]
Wow. It really works. Thank you for your reply.
